imports:
    - { resource: parameters.yml }

services:
    garage.manager:
        class: Ecomitize\Garage\VehicleManager
        arguments: ['@vehicle.factory', '%garage.vehicles%']

    bmv.vehicle:
        class: Framework\Vehicle\Vehicle
        lazy:  true
        arguments: ["%bmv.name%", "@command.factory"]
        calls:
            - [addCommands, ["%bmv.commands%"]]

    airplane.vehicle:
        class: Framework\Vehicle\Vehicle
        lazy:  true
        arguments: ["%airplane.name%", "@command.factory"]
        calls:
            - [addCommands, ["%airplane.commands%"]]


    start.command:
        lazy:  true
        class: Ecomitize\Command\StartCommand

    musicOn.command:
        lazy:  true
        class: Ecomitize\Command\MusicOnCommand

    takeOff.command:
        lazy:  true
        class: Ecomitize\Command\TakeOffCommand

    fly.command:
        lazy:  true
        class: Ecomitize\Command\FlyCommand


#    gelf.transport:
#        class: Monolog\Handler\StreamHandler
#        arguments: ["%graylog.file_path%"]
#
#    gelf.publisher:
#        class: Gelf\Publisher
#        arguments: ["@gelf.transport"]
#
#    monolog.gelf_handler:
#        class: Monolog\Handler\GelfHandler
#        arguments: ["@gelf.publisher", "%monolog.handler.debug_level%"]

    monolog.handler:
        class: Monolog\Handler\StreamHandler
        arguments: ["%graylog.file_path%"]
        public: false

    monolog.logger:
        class: Monolog\Logger
        arguments: ["%monolog.logger.name%"]
        calls:
            - [pushHandler, ["@monolog.handler"]]

